### ISSUE TITLE
Errors while scanning packages

### ISSUE THREAD

**Issue by puiesabu** [rabarar/meteor-flot#4]
This is the error shown during `mrt add flot`

```
While building package `flot`:
error: File not found: /lib/jquery.flot.min.js
error: File not found: /lib/jquery.flot.pie.min.js
error: File not found: /lib/jquery.flot.resize.min.js

/Users/harryng/.nvm/v0.10.26/lib/node_modules/meteorite/lib/command.js:35
          throw "Command exited with " + code + "/" + signal;
```

**Comment by gjolund** [comment]
Hey @puiesabu,

This package is ancient, but I have made the necessary changes and everything seems to be working in the example. Give it a shot and let me know if you have any problems.

**Comment by gjolund** [comment]
Actually...

This package is so old that atmosphere no longer recognizes me as the owner and won't let me push up the changes.

I created an [ issue on atmosphere ](https://github.com/percolatestudio/atmosphere-beta/issues/157), but honestly this package is super simple and you can just fork it and publish your own package if you are in desperate need.

You can bump the issue I created to try to get a speedier response from the atmosphere team.
